name: run commands through ssh
on:
  push:
    branches:
      - ssh
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
          SERVICE_NAME: ${{secrets.SERVICE_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd deployment
              sudo pwd
              ls
              sudo docker-compose down
              yes | sudo docker image prune
              sudo docker-compose stop ${SERVICE_NAME}
              sudo docker-compose rm -f ${SERVICE_NAME}
              sudo docker-compose pull ${SERVICE_NAME}
              sudo docker-compose up -d ${SERVICE_NAME}
              '
